// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

import {Test} from "forge-std/Test.sol";

import {PortfolioMath} from "../src/portfolio/PortfolioMath.sol";

/// @notice Pins `PortfolioMath` to `test/vectors/portfolio_vectors.json`, 225 cases generated by
///   `tools/reference/portfolio_reference.py` in exact rational/integer arithmetic — an implementation
///   written independently of the Solidity one. Regenerate the vectors whenever the math changes and keep
///   `n_cases` in sync, exactly like the pricing vectors.
contract PortfolioVectorsTest is Test {
    string internal json;
    uint256 internal caseCount;

    function setUp() public {
        json = vm.readFile("test/vectors/portfolio_vectors.json");
        caseCount = vm.parseJsonUint(json, ".n_cases");
        assertEq(caseCount, 225, "n_cases drifted from the generator");
    }

    function _u(uint256 i, string memory field) internal view returns (uint256) {
        return vm.parseJsonUint(json, string.concat(".cases[", vm.toString(i), "].", field));
    }

    /// @dev Batched purely for gas, mirroring MarketPricing's vector tests.
    function _run(uint256 from, uint256 to) internal view {
        for (uint256 i = from; i < to && i < caseCount; i++) {
            uint256 s = _u(i, "s");
            uint256 h = _u(i, "h");
            uint256 c = _u(i, "c");
            uint256 xWad = PortfolioMath.normalizedOutcome(_u(i, "final_variance"), uint64(_u(i, "cap_variance")));
            assertEq(xWad, _u(i, "x_wad"), "x");

            assertEq(PortfolioMath.reserve(h, c, s), _u(i, "reserve"), "reserve");

            (uint256 hp, uint256 cp) = PortfolioMath.finalPayouts(xWad, s);
            assertEq(hp, _u(i, "high_ppu"), "high ppu");
            assertEq(cp, _u(i, "calm_ppu"), "calm ppu");
            assertEq(hp + cp, s, "complement identity");

            uint256 locked = PortfolioMath.finalSideLiability(h, hp) + PortfolioMath.finalSideLiability(c, cp);
            assertEq(locked, _u(i, "final_locked"), "final locked");
            assertGe(_u(i, "reserve"), _u(i, "worst_case"), "reserve bounds grid worst case");
            assertGe(_u(i, "reserve"), locked, "reserve bounds the realized liabilities");
        }
    }

    function test_vectors_00() public view {
        _run(0, 45);
    }

    function test_vectors_45() public view {
        _run(45, 90);
    }

    function test_vectors_90() public view {
        _run(90, 135);
    }

    function test_vectors_135() public view {
        _run(135, 180);
    }

    function test_vectors_180() public view {
        _run(180, 225);
    }
}
