//! Off-chain replica of the realized-variance math (ARCHITECTURE §1):
//!
//! ```text
//! r_i = ln(P_i / P_{i-1})            i = 1..n
//! RV  = Σ r_i² · 31_536_000 / (expiry − start)      (annualized; WAD on-chain)
//! ```
//! The cap (`RVc = min(RV, capVariance)`) is a settlement-leg concern and is **not** applied here.

pub const SECONDS_PER_YEAR: f64 = 31_536_000.0;

/// Log returns between consecutive prices (`prices.len() - 1` entries).
pub fn log_returns(prices: &[f64]) -> Vec<f64> {
    prices.windows(2).map(|w| (w[1] / w[0]).ln()).collect()
}

/// Annualized realized variance over `span_seconds` for the sampled `prices`.
pub fn realized_variance(prices: &[f64], span_seconds: u64) -> f64 {
    if prices.len() < 2 || span_seconds == 0 {
        return 0.0;
    }
    let sum_sq: f64 = log_returns(prices).iter().map(|r| r * r).sum();
    sum_sq * SECONDS_PER_YEAR / span_seconds as f64
}

/// Annualized volatility = sqrt(variance).
pub fn vol(variance: f64) -> f64 {
    variance.max(0.0).sqrt()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn close(a: f64, b: f64, rel: f64) -> bool {
        if b == 0.0 {
            return a.abs() < 1e-12;
        }
        ((a - b) / b).abs() < rel
    }

    // Vectors generated by tools/rv_check.py (Decimal precision).
    #[test]
    fn flat_path_has_zero_variance() {
        let prices = vec![3000.0; 25];
        assert_eq!(realized_variance(&prices, 86_400), 0.0);
        assert!(log_returns(&prices).iter().all(|r| *r == 0.0));
    }

    #[test]
    fn alternating_one_percent_hourly_for_24h() {
        let mut p = vec![3000.0f64];
        for i in 0..24 {
            let last = *p.last().unwrap();
            p.push(if i % 2 == 0 { last * 1.01 } else { last / 1.01 });
        }
        let rv = realized_variance(&p, 86_400);
        // closed form: 24 · ln(1.01)² · 365
        let closed = 24.0 * (1.01f64).ln().powi(2) * 365.0;
        assert!(close(rv, closed, 1e-9), "rv={rv} closed={closed}");
        assert!(close(rv, 0.867319576606575, 1e-9), "python vector: rv={rv}");
        assert!(close(vol(rv), 0.93129, 1e-4));
    }

    #[test]
    fn cap_is_not_applied_off_chain() {
        // +50% in one hour then flat: variance 1440.16 >> cap 1.0 (100% vol) stays uncapped here.
        let rv = realized_variance(&[2000.0, 3000.0, 3000.0], 3600);
        assert!(close(rv, 1440.1611161041292, 1e-9), "rv={rv}");
        let cap = 1.0;
        assert!(rv > cap);
    }

    #[test]
    fn weekly_daily_vector() {
        let p = [2500.0, 2450.0, 2600.0, 2580.0, 2700.0, 2650.0, 2610.0];
        let rv = realized_variance(&p, 6 * 86_400);
        assert!(close(rv, 0.4043270459734665, 1e-9), "rv={rv}");
    }

    #[test]
    fn degenerate_inputs() {
        assert_eq!(realized_variance(&[], 100), 0.0);
        assert_eq!(realized_variance(&[1.0], 100), 0.0);
        assert_eq!(realized_variance(&[1.0, 2.0], 0), 0.0);
    }
}
