// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

import {Math} from "@openzeppelin/contracts/utils/math/Math.sol";
import {SafeCast} from "@openzeppelin/contracts/utils/math/SafeCast.sol";
import {FixedPointMathLib} from "solady/src/utils/FixedPointMathLib.sol";

/// @notice Every executable number in a Tremor market, as integer-only pure math: inventory-skew decay,
///   the forward and projected variance, the bid/ask pair, the integral fill prices for ISSUE and EXIT,
///   the final payout, and the collateral liability of a given outstanding position.
///
///   The engine (`TremorMarketEngine`), the read model (`TremorLens`) and the controller
///   (`VarianceSeriesFactory`) all call into this one library, so a quote, a swap and a UI figure cannot
///   drift apart. `test/vectors/pricing_vectors.json`, generated by `tools/reference/pricing_reference.py`
///   at 60 decimal digits of precision, pins every formula here.
///
///   Rounding always favours the maker, which is the writer's collateralised vault:
///     ISSUE exact-in    units round down
///     ISSUE exact-out   premium rounds up
///     EXIT  exact-in    proceeds round down
///     SETTLE exact-in   proceeds round down
///     liability         rounds up
library VariancePricing {
    error SpreadTooWide(uint16 halfSpreadBps);

    uint256 internal constant WAD = 1e18;
    uint256 internal constant WAD2 = 1e36;
    uint256 internal constant BPS = 10_000;
    uint256 internal constant YEAR = 31_536_000;
    int256 internal constant LN_HALF_WAD = -693_147_180_559_945_309; // ln(1/2) * 1e18

    // ------------------------------------------------------------------ inventory skew

    /// @notice `skew * 2^(-dt / halfLife)`, sign preserved. `halfLife == 0` means the skew never decays.
    /// @dev Integer division truncates toward zero, so decay can only ever shrink the magnitude.
    function decaySkew(int256 skew, uint256 dt, uint32 halfLife) internal pure returns (int256) {
        if (skew == 0 || dt == 0 || halfLife == 0) return skew;
        int256 x = LN_HALF_WAD * SafeCast.toInt256(dt) / int256(uint256(halfLife));
        int256 factor = FixedPointMathLib.expWad(x); // in [0, 1e18]; 0 for very negative x
        return skew * factor / int256(WAD);
    }

    /// @notice The market's forward variance: `clamp(anchorVariance + decayedSkew, 0, capVariance)`.
    function forwardVariance(uint64 anchorVariance, int256 decayedSkew, uint64 capVariance)
        internal
        pure
        returns (uint256)
    {
        int256 v = int256(uint256(anchorVariance)) + decayedSkew;
        if (v <= 0) return 0;
        return uint256(v) > capVariance ? capVariance : uint256(v);
    }

    // ------------------------------------------------------------------ projection

    /// @notice Variance the market currently projects for the whole window:
    ///   `(realizedSoFar * elapsed + forward * remaining) / duration`.
    ///
    ///   `elapsed` is `checkpointedThrough - start` and `remaining` is `expiry - checkpointedThrough`, so
    ///   before the window opens the projection is exactly the forward variance and at expiry it is exactly
    ///   the realized variance. Unlike the bid and ask this value is NOT clamped to the cap: it is the
    ///   honest projection, and clamping belongs to the price, not to the measurement.
    function projectedVariance(uint256 realizedSoFar, uint256 elapsed, uint256 forward, uint256 remaining)
        internal
        pure
        returns (uint256)
    {
        uint256 duration = elapsed + remaining;
        if (duration == 0) return forward;
        return (realizedSoFar * elapsed + forward * remaining) / duration;
    }

    /// @notice Annualized realized variance of the samples accumulated so far.
    /// @param sumSquaredReturns WAD sum of squared log returns over `elapsed` seconds
    function annualize(uint256 sumSquaredReturns, uint256 elapsed) internal pure returns (uint256) {
        if (elapsed == 0) return 0;
        return Math.mulDiv(sumSquaredReturns, YEAR, elapsed);
    }

    // ------------------------------------------------------------------ bid and ask

    /// @notice Half-spread applied to the projection, then clamped to the cap so a quote can never promise
    ///   more than a receipt can pay.
    /// @return bidVariance floor(projected * (1 - s)), capped
    /// @return askVariance ceil(projected * (1 + s)), capped
    function bidAskVariance(uint256 projected, uint16 halfSpreadBps, uint64 capVariance)
        internal
        pure
        returns (uint256 bidVariance, uint256 askVariance)
    {
        require(halfSpreadBps < BPS, SpreadTooWide(halfSpreadBps));
        askVariance = Math.mulDiv(projected, BPS + halfSpreadBps, BPS, Math.Rounding.Ceil);
        bidVariance = Math.mulDiv(projected, BPS - halfSpreadBps, BPS, Math.Rounding.Floor);
        if (askVariance > capVariance) askVariance = capVariance;
        if (bidVariance > capVariance) bidVariance = capVariance;
    }

    /// @notice Quote-token amount per 1e18 receipt units at a given variance (floor).
    function perUnitPrice(uint128 unitNotional, uint256 variance) internal pure returns (uint256) {
        return Math.mulDiv(unitNotional, variance, WAD, Math.Rounding.Floor);
    }

    /// @notice The most a single receipt unit can ever pay: `floor(unitNotional * cap / 1e18)`.
    function maxPayoutPerUnit(uint128 unitNotional, uint64 capVariance) internal pure returns (uint256) {
        return Math.mulDiv(unitNotional, capVariance, WAD, Math.Rounding.Floor);
    }

    // ------------------------------------------------------------------ inventory impact slope

    /// @notice How much the ISSUE ask variance moves per 1e18 units sold (rounded up, maker-favouring).
    ///
    ///   Selling `u` units raises the stored skew by `impactPerUnit * u / 1e18`; the skew reaches the ask
    ///   through the projection weight `remaining / duration` and the ask multiplier `(1 + s)`. Both are
    ///   affine, so the composed marginal ask is affine in `u` with exactly this slope — which is what makes
    ///   the closed-form fill integrals below exact rather than approximate.
    function askImpactSlope(uint64 impactPerUnit, uint256 remaining, uint256 duration, uint16 halfSpreadBps)
        internal
        pure
        returns (uint256)
    {
        if (impactPerUnit == 0 || remaining == 0 || duration == 0) return 0;
        return Math.mulDiv(uint256(impactPerUnit) * remaining, BPS + halfSpreadBps, duration * BPS, Math.Rounding.Ceil);
    }

    /// @notice How much the EXIT bid variance moves per 1e18 units bought back (rounded down).
    function bidImpactSlope(uint64 impactPerUnit, uint256 remaining, uint256 duration, uint16 halfSpreadBps)
        internal
        pure
        returns (uint256)
    {
        if (impactPerUnit == 0 || remaining == 0 || duration == 0) return 0;
        return Math.mulDiv(uint256(impactPerUnit) * remaining, BPS - halfSpreadBps, duration * BPS, Math.Rounding.Floor);
    }

    // ------------------------------------------------------------------ ISSUE fill

    /// @notice Premium (quote base units, ceil) for `units` when the marginal ask variance starts at
    ///   `askVariance` and rises by `slope` per 1e18 units:
    ///     premium(u) = ceil( unitNotional * (askVariance * u + slope * u^2 / 2e18) / 1e36 )
    function issuePremium(uint256 askVariance, uint256 slope, uint128 unitNotional, uint256 units)
        internal
        pure
        returns (uint256)
    {
        if (units == 0) return 0;
        uint256 integral = askVariance * units + Math.mulDiv(slope * units, units, 2 * WAD, Math.Rounding.Ceil);
        return Math.mulDiv(unitNotional, integral, WAD2, Math.Rounding.Ceil);
    }

    /// @notice Units (floor) affordable with `amountIn` quote base units against the same rising ask.
    /// @dev Inverts `premium(u)` in the cancellation-free form
    ///        u = 2X / (askVariance + ceil(sqrt(askVariance^2 + 2 * slope * X / 1e18))),  X = amountIn * 1e36 / unitNotional
    ///   which degenerates to `X / askVariance` when the slope is zero. The square root rounds up, so the
    ///   taker receives no more units than the exact real-valued solution.
    function issueUnitsFor(uint256 askVariance, uint256 slope, uint128 unitNotional, uint256 amountIn)
        internal
        pure
        returns (uint256)
    {
        if (askVariance == 0 || amountIn == 0) return 0;
        uint256 x = Math.mulDiv(amountIn, WAD2, unitNotional);
        if (slope == 0) return x / askVariance;
        uint256 discriminant = askVariance * askVariance + Math.mulDiv(2 * slope, x, WAD, Math.Rounding.Ceil);
        uint256 root = FixedPointMathLib.sqrt(discriminant);
        if (root * root < discriminant) root += 1;
        return (2 * x) / (askVariance + root);
    }

    /// @notice Units that can be sold before the marginal ask variance would exceed the cap.
    function issueUnitsToCap(uint256 askVariance, uint256 slope, uint64 capVariance) internal pure returns (uint256) {
        if (askVariance >= capVariance) return 0;
        if (slope == 0) return type(uint256).max;
        return (capVariance - askVariance) * WAD / slope;
    }

    /// @notice Units that fit in `freeCollateral` on top of `outstandingUnits` already reserved at
    ///   `lockedLiability`, given full-cap reservation. Returns 0 when nothing more fits.
    /// @dev Solves `ceil((outstanding + u) * unitNotional * cap / 1e36) <= lockedLiability + freeCollateral`.
    function issueUnitsToCollateral(
        uint256 outstandingUnits,
        uint256 lockedLiability,
        uint256 freeCollateral,
        uint128 unitNotional,
        uint64 capVariance
    ) internal pure returns (uint256) {
        uint256 allowed = lockedLiability + freeCollateral;
        uint256 denominator = uint256(unitNotional) * capVariance;
        if (denominator == 0) return type(uint256).max;
        uint256 totalUnits = Math.mulDiv(allowed, WAD2, denominator);
        return totalUnits > outstandingUnits ? totalUnits - outstandingUnits : 0;
    }

    // ------------------------------------------------------------------ EXIT fill

    /// @notice Proceeds (quote base units, floor) for selling `units` back when the marginal bid variance
    ///   starts at `bidVariance` and falls by `slope` per 1e18 units:
    ///     proceeds(u) = floor( unitNotional * (bidVariance * u - slope * u^2 / 2e18) / 1e36 )
    /// @dev The caller must clamp `units` to `exitUnitsToZeroBid` first; this reverts rather than
    ///   underflowing if the bracket would go negative.
    function exitProceeds(uint256 bidVariance, uint256 slope, uint128 unitNotional, uint256 units)
        internal
        pure
        returns (uint256)
    {
        if (units == 0) return 0;
        uint256 gross = bidVariance * units;
        uint256 impact = Math.mulDiv(slope * units, units, 2 * WAD, Math.Rounding.Floor);
        return Math.mulDiv(unitNotional, gross - impact, WAD2, Math.Rounding.Floor);
    }

    /// @notice Units that can be bought back before the marginal bid variance would reach zero.
    function exitUnitsToZeroBid(uint256 bidVariance, uint256 slope) internal pure returns (uint256) {
        if (slope == 0) return type(uint256).max;
        return bidVariance * WAD / slope;
    }

    // ------------------------------------------------------------------ settlement

    /// @notice `floor(unitNotional * min(finalVariance, cap) / 1e18)`.
    function payoutPerUnit(uint256 finalVariance, uint64 capVariance, uint128 unitNotional)
        internal
        pure
        returns (uint256)
    {
        uint256 capped = finalVariance < capVariance ? finalVariance : capVariance;
        return Math.mulDiv(unitNotional, capped, WAD, Math.Rounding.Floor);
    }

    /// @notice `floor(units * payoutPerUnit / 1e18)`.
    function settleProceeds(uint256 units, uint256 payoutPerUnit_) internal pure returns (uint256) {
        return Math.mulDiv(units, payoutPerUnit_, WAD, Math.Rounding.Floor);
    }

    // ------------------------------------------------------------------ liability

    /// @notice Collateral that must stay locked for `units` outstanding before finalization:
    ///   `ceil(units * unitNotional * cap / 1e36)`.
    /// @dev Computed from the aggregate outstanding position, never as a rounded per-unit figure times a
    ///   count, so splitting one fill into many cannot drift the reservation.
    function maxLiability(uint256 units, uint128 unitNotional, uint64 capVariance) internal pure returns (uint256) {
        if (units == 0) return 0;
        return Math.mulDiv(units * unitNotional, capVariance, WAD2, Math.Rounding.Ceil);
    }

    /// @notice Collateral that must stay locked for `units` outstanding after finalization:
    ///   `ceil(units * payoutPerUnit / 1e18)`.
    function finalLiability(uint256 units, uint256 payoutPerUnit_) internal pure returns (uint256) {
        if (units == 0) return 0;
        return Math.mulDiv(units, payoutPerUnit_, WAD, Math.Rounding.Ceil);
    }
}
